export const routes = {
    landing: '/',
    signin: '/',
    signup: '/signup',
    signupSuccess: '/signup/success',
    recoverPassword: '/recover-password',
    recoverSuccess: '/recover-password/success',
    resetPassword: '/reset-password',
    resetSuccess: '/reset-password/success',
    termsConditions: '/terms-and-conditions',
    join: '/join',
    joinSuccess: '/join/success',
    verify: '/verify',
    app: '/app',
    _app: {
        dashboard: '/app/dashboard',
        messages: '/app/messages',
        settings: '/app/settings',
    },
};
